
#注册中心客户端
eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    metadata-map:
      version: 2
      gray: true
  client:
    serviceUrl:
      defaultZone: http://192.168.0.1:1111/eureka/

spring:
  datasource:
    url: jdbc:mysql://192.168.0.1:3306/tenant_user?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: 1q2w3e
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      maxLifetime: 1765000
      maximumPoolSize: 12


