server:
  port: 32004
eureka:
  instance:
    ip-address: 10.16.8.121
    instance-id: ${eureka.instance.ip-address}:${server.port}
    prefer-ip-address: true

#  client:
#    serviceUrl:
#      defaultZone: http://register-0.register.default.svc.cluster.local:1111/eureka/

#spring:
#  datasource:
#    url: jdbc:mysql://mysql-0.mysql.default.svc.cluster.local:3306/tenant_user?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
#    username: root
#    password: mysql
#    driverClassName: com.mysql.jdbc.Driver
#    hikari:
#      maxLifetime: 1765000
#      maximumPoolSize: 50
#
