
#注册中心客户端
eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    metadata-map:
      version: 2
      gray: true
  client:
    serviceUrl:
      defaultZone: http://saasp-register-0.saasp-register.saas-iot.svc.cluster.local:1111/eureka/

spring:
  datasource:
    url: jdbc:mysql://xx.com/tenant_user_iot?useUnicode=true&amp;characterEncoding=utf-8
    username: xx
    password: xx&kZt
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      maxLifetime: 1765000
      maximumPoolSize: 12


